### ISSUE TITLE
Wallet app

### ISSUE THREAD

**Issue by saipraveenbammidi** [Psyhackological/AAA#17]
You can check out Ivy wallet.

**Comment by Psyhackological** [comment]
Alright, but isn't it
> Freemium • Proprietary?

**Comment by XXDRD** [comment]
> Alright, but isn't it
> 
> > Freemium • Proprietary?

it is opensource

**Comment by Psyhackological** [comment]
Oh. AlternativeTo tricked me. Alright, thanks for suggesting!

**Comment by saipraveenbammidi** [comment]
> Oh. AlternativeTo tricked me. Alright, thanks for suggesting!

You're welcome.

**Comment by Psyhackological** [comment]
I've [updated](https://github.com/Psyhackological/AAA/commit/dc738c3ecdc45b4c8ee6fc9dbfc64641b6bf00f5) the [PRIVACY.md](https://github.com/Psyhackological/AAA/blob/main/PRIVACY.md) and I've decided not to include Ivy Wallter, because of [Google Firebase Analytics](https://reports.exodus-privacy.eu.org/en/trackers/49/).
