### ISSUE TITLE
Calculator++

### ISSUE THREAD

**Issue by mxxcon** [Psyhackological/AAA#7]
Hello.
Google Play says that Calculator++ has ads and F-Droid says that Calculator++ tracks user activities.

**Comment by Psyhackological** [comment]
Interesting. I've done some research and turns out that [Google Play](https://reports.exodus-privacy.eu.org/en/reports/44561/) version is worse than [F-Droid](https://reports.exodus-privacy.eu.org/en/reports/org.solovyev.android.calculator/latest/) one. Not sure what to do with it though. What do you think?

**Comment by mxxcon** [comment]
It violates 2 of your rules, so it seems like grounds for delisting. 
Also, it was last updated in 2018.. not that a calculator app needs constant development 🙂 but in 4 years there's gotta be something to improve..

**Comment by mxxcon** [comment]
Ultimately it's your repo and your call🙂, but keeping it would be misleading to others since you claim that your list contains only apps that are ads-free.. If people fully rely on your word and install it from Play Store w/o looking at the tags there, they will be greeted with banner ads.. 🤷‍♂️

**Comment by Psyhackological** [comment]
Yeah I know. I'm thinking about just deleting the link and doing ~~Google Play~~ in some scenarios. What do you think?

**Comment by Psyhackological** [comment]
I hope [this](https://github.com/Psyhackological/AAA/commit/5595906745f7f81089984544cef72326a6464058) is enough.
